### ISSUE TITLE
error if CSS @media is not followed by a space

### ISSUE THREAD

**Issue by niklaushug** [kristerkari/stylelint-scss#101]
Stylelint errors out if CSS's @media and condition is not separate by a space and some rules are active.

`$ node node_modules/stylelint/bin/stylelint.js "tescht/**/*.scss"`
TypeError: Cannot read property '1' of null
    at findCommentsInRaws (/Users/tocco/Projects/tocco-client/node_modules/stylelint-scss/dist/utils/findCommentsInRaws.js:91:124)
    at calculationOperatorSpaceChecker (/Users/tocco/Projects/tocco-client/node_modules/stylelint-scss/dist/rules/operator-no-unspaced/index.js:221:33)
    at /Users/tocco/Projects/tocco-client/node_modules/stylelint-scss/dist/rules/operator-no-newline-before/index.js:17:61
    at Promise.resolve.then (/Users/tocco/Projects/tocco-client/node_modules/stylelint/lib/lintSource.js:122:52)

this CSS causes an error
`@media(min-width: 480px) {
    .nonsense{
        content: 'nonsense';
    }
}`

this CSS causes no error
`@media (min-width: 480px) {
    .nonsense{
        content: 'nonsense';
    }
}`

If I deactivate subsequent rules both @media variants work fine (with and without space).
- "scss/operator-no-newline-after": true,
- "scss/operator-no-newline-before": true,
- "scss/operator-no-unspaced": true,

node v7.5.0 is used
npm  v4.3.0 is used

**Comment by dryoma** [comment]
Hi @niklaushug 

Thanks for noticing and reporting this, fixed in 1.4.2
