### ISSUE TITLE
New install results in TypeError: Cannot read property 'rejected' of undefined

### ISSUE THREAD

**Issue by sardell** [kristerkari/stylelint-scss#238]
I'm running into the same problem as seen in issue #145. However, I'm using the latest stylelint-scss release.

## My environment:
Mac OS 10.13.2
Node 9.11.1
npm 5.6.0
stylelint-scss 3.0.1
stylelint 9.2.0

## Steps to reproduce
I followed the instructions in the [Installation and Usage section](https://github.com/kristerkari/stylelint-scss#installation-and-usage). Then I ran `stylelint "path/to/my/styles/**/*.scss"`, which resulted in the following error.

```
TypeError: Cannot read property 'rejected' of undefined
    at Object.<anonymous> (/Users/me/myproject/node_modules/stylelint-scss/dist/rules/at-rule-no-unknown/index.js:64:59)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/me/myproject/node_modules/stylelint-scss/dist/rules/index.js:75:24)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
```

My config file is basic and looks like this:
```
{
	"plugins": [
	  "stylelint-scss"
	],
	"rules": {
	  "scss/selector-no-redundant-nesting-selector": true
	}
}
```

**Comment by kristerkari** [comment]
Thanks for the report!

Hmm.. I was not able to reproduce the bug with the settings that you listed. 

The error is thrown when accessing the base rule from stylelint:

```js
_stylelint.rules[ruleToCheckAgainst].messages.rejected
```

The `messages` property is unknown and that throws. I really have no idea why it does not find the stylelint rule it tries to access.

Did you already try to remove `node_modules` folder and installing again?

**Comment by sardell** [comment]
I should have already done that, and of course that was the resolution to my issue. :flushed:

Thank you for your quick response!
