### ISSUE TITLE
`declaration-nested-properties: "always"` emits `Expected a pseudo-class or pseudo-element.` 

### ISSUE THREAD

**Issue by JounQin** [kristerkari/stylelint-scss#359]
```scss
a {
  font: {
    size: 10px;
    weight: 400;
  }
}
```

The error is from `postcss-selector-parser`

```sh
Error: Expected a pseudo-class or pseudo-element.
    at Root._error (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint-scss/node_modules/postcss-selector-parser/dist/parser.js:160:16)
    at Root.error (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint-scss/node_modules/postcss-selector-parser/dist/selectors/root.js:43:19)
    at Parser.error (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint-scss/node_modules/postcss-selector-parser/dist/parser.js:726:21)
    at Parser.expected (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint-scss/node_modules/postcss-selector-parser/dist/parser.js:1113:19)
    at Parser.pseudo (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint-scss/node_modules/postcss-selector-parser/dist/parser.js:861:19)
    at Parser.parse (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint-scss/node_modules/postcss-selector-parser/dist/parser.js:1064:14)
    at Parser.loop (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint-scss/node_modules/postcss-selector-parser/dist/parser.js:1023:12)
    at new Parser (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint-scss/node_modules/postcss-selector-parser/dist/parser.js:150:10)
    at Processor._root (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint-scss/node_modules/postcss-selector-parser/dist/processor.js:55:18)
    at /Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint-scss/node_modules/postcss-selector-parser/dist/processor.js:74:26
```

**Comment by kristerkari** [comment]
Thanks @JounQin !

I tried adding a unit test with the example that you gave, but it does not throw any error. Would you have some example to shere that throws the error?

**Comment by JounQin** [comment]
https://github.com/1stG/configs/blob/master/packages/stylelint-config/scss.js#L15

You can clone the repository and change this line, and then simply run `yarn lint:style:scss`

**Comment by kristerkari** [comment]
Thanks @JounQin! The error is actually coming from the `selector-nest-combinators` rule. I managed to reproduce the error with a unit test, so I'll prepare a fix for that rule.

**Comment by JounQin** [comment]
Thanks for your quick response and fix.

**Comment by SharakPL** [comment]
@kristerkari it seems this bug is still present. Throws error every time I want to add another pseudo-class before existing one:

https://user-images.githubusercontent.com/5007456/114281630-aeba6380-9a3f-11eb-8336-517b851849da.mp4

I use v.3.19.
